[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NPM_FLAGS = "--include=optional"
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"