name: Invoke Netlify Function
on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight
  workflow_dispatch:

jobs:
  triggerNetlifyFunction:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Netlify Function
      run: curl -X POST 'https://your-netlify-function-url'
