name: Process Documents

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight

jobs:
  process_docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get install -y jq
        # Install any other necessary dependencies

    - name: Fetch documents and process in batches
      env:
        NETLIFY_FUNCTION_URL: ${{ secrets.NETLIFY_FUNCTION_URL }}
      run: |
        chmod +x process_docs.sh
        ./process_docs.sh
